### ISSUE TITLE
owned_book methods return errors

### ISSUE THREAD

**Issue by gchrlsyslib** [sefakilic/goodreads#14]
I'm using 0.2.4 with Django for a web app, and I'm encountering repeated errors when accessing owned_book instances.

Thus far:

owned_book.GoodreadsOwnedBook.book
owned_book.GoodreadsOwnedBook.gid
owned_book.GoodreadsOwnedBook.current_owner

All give "string indices must be integers" errors when called.

**Comment by gchrlsyslib** [comment]
Error found; for loop iterates through the dictionary created by user.owned_books() generated key name strings, not calling GoodreadsOwnedBook instances within the dictionary. Standard Python behavior, not standard Django behavior; minor code modifications fixed the issue.

**Comment by lkadin** [comment]
Similar issue.

Trying to get owned books for a user but get the following:

books =  user.owned_books()
  File "build\bdist.win32\egg\goodreads\user.py", line 54, in owned_books
    {'page': page, 'format': 'xml'})
  File "build\bdist.win32\egg\goodreads\session.py", line 54, in get
    return xmltodict.parse(resp.content)['GoodreadsResponse']
  File "build\bdist.win32\egg\xmltodict.py", line 248, in parse
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
