### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by dhitals** [sefakilic/goodreads#20]
Hi, I am having trouble importing. I am in a virtualenv and can import `goodreads` but not the `client`, which cannot import `sessions`. I have verified that it is right package, and that the path is correct. Please see exact error below:
```
## I can import goodreads
>>> import goodreads

## but not the client
>>> from goodreads import client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Envs/flask/lib/python3.5/site-packages/goodreads/client.py", line 2, 
    from session import GoodreadsSession
ImportError: No module named 'session'
```
I am using python3, but there should not be an error with import?

**Comment by dhitals** [comment]
OK, fixed. Mostly a 2to3 issue. I am happily running on python3 now.

**Comment by DenitsaKostova** [comment]
How did you fix this issue? I have the same problem?

**Comment by sefakilic** [comment]
Fixed now.
