### ISSUE TITLE
Changed raw_input() into input() for Python

### ISSUE THREAD

**Issue by arashout** [sefakilic/goodreads#21]
In: 
goodreads/goodreads/client.py line 46 
I believe that that 
"while raw_input("Have you authorized me? (y/n)") != 'y':"
Should be
"while input("Have you authorized me? (y/n)") != 'y':"
Right now it doesn't work in Python 3.

**Comment by sefakilic** [comment]
fixed in 98c6bd8acde9fe0d521f0bc07e043634142ee314
