### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'client'

### ISSUE THREAD

**Issue by arashout** [sefakilic/goodreads#22]
Hey I'm not sure if this a bug or if I am doing it incorrectly. I am trying to access my owned books by doing this:
```
from goodreads import client

api_key = "my api key"
api_secret = "my secret"
gc = client.GoodreadsClient(api_key, api_secret)
gc.authenticate()

user_id = my good reads id
user = gc.user(user_id)
owned_books = user.owned_books()
for owned_book in owned_books:
    print(owned_book.book)
```

**Comment by sefakilic** [comment]
Do you have only one owned book? It wasn't working correctly for the case that there is a single owned book. Fixed and PyPI package updated. Please let me know if you continue having the issue.

**Comment by arashout** [comment]
Hey sefakilic it still doesn't work. I can confirm I have books owned because this script:
```
from goodreads import client

api_key = "XXXXX"
api_secret = "XXXXX"
gc = client.GoodreadsClient(api_key, api_secret)
gc.authenticate()

user_id = XXXXXX
user = gc.user(user_id)
owned_books = user.owned_books()
for owned_book in owned_books:
    print(owned_book.link())
```
Produces this output: 
```
Have you authorized me? (y/n)y
https://www.goodreads.com/owned_books/42981652
https://www.goodreads.com/owned_books/42981655
https://www.goodreads.com/owned_books/42981654
https://www.goodreads.com/owned_books/42981647
https://www.goodreads.com/owned_books/42981650
```

**Comment by arashout** [comment]
I am really just trying to get a list of books I have read. There might be a better way of simply accessing my "read" shelf and listing the books off there? But I don't know how to do that.
