### ISSUE TITLE
How to get access token secret?

### ISSUE THREAD

**Issue by aidiss** [sefakilic/goodreads#24]
I was able to get access token. But how can I get access token secret?

**Comment by sefakilic** [comment]
You can get a API key and secret at https://www.goodreads.com/api/keys

**Comment by aidiss** [comment]
I can get app key and secret at your link, I believe.
I call gc.authenticate() and it gets me to https://www.goodreads.com/?oauth_token={auth_token}&authorize=1
What abotu token secret?
