### ISSUE TITLE
Import Error : Client

### ISSUE THREAD

**Issue by jaskiratr** [sefakilic/goodreads#3]
from goodreads import client
	gc = client.GoodreadsClient(<api_key>, <api_secret>)

The above code returns the following error: 

	ImportError: cannot import name client

Is there any way to fix this? Why would this show up?
Any help will be appreciated!
Thanks

**Comment by sefakilic** [comment]
It works properly for me. How did you install the goodreads package or did you  download the source?

What I did was:
$ sudo python setup.py install
$ ipython
$ > from goodreads import client

**Comment by jaskiratr** [comment]
I downloaded the repository, cd into it and ran the following command.
	sudo python setup.py install

**Comment by jaskiratr** [comment]
This is the exact error generated: 

	>>> from goodreads import client
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/Library/Python/2.7/site-packages/goodreads/__init__.py", line 5, in <module>
	    from .client import Client, GoodreadsRequestError, GoodreadsSession
	ImportError: cannot import name Client

**Comment by sefakilic** [comment]
I guess you're confusing this library with another Goodreads API wrapper, [goodreads-py](https://github.com/GrumpyRainbow/goodreads-py).

The line

    from .client import Client, GoodreadsRequestError, GoodreadsSession

is from goodreads-py library, not this one.

**Comment by jaskiratr** [comment]
Yes, it was a dumb conflict in libraries I couldn't identify. Apologies for the trouble.
Thank you for your help!

**Comment by dhitals** [comment]
Hi, I am having trouble importing as well. I can import `goodreads` but not the `client`, which cannot import `sessions`. I have verified that it is right package, and that the path is correct. Please see exact error below:
``
## I can import goodreads
>>> import goodreads

## but not the client
>>> from goodreads import client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saurav/Envs/flask/lib/python3.5/site-packages/goodreads/client.py", line 2, 
    from session import GoodreadsSession
ImportError: No module named 'session'
``

**Comment by caggursoy** [comment]
@sefakilic sorry for bothering but @jaskiratr did you solve the problem? I've been working on it and couldn't manage to work it.
Cheers!

**Comment by antoinecomp** [comment]
Same thing and I'm on Windows. Can't use the sudo command.
