### ISSUE TITLE
parsing issue

### ISSUE THREAD

**Issue by FatNarwhal** [sefakilic/goodreads#5]
Hi! Sorry if this is a stupid question, I new to programming and seem to be getting this error message on Windows when I try to go through the readme:

    C:\Python>python2 goodreads_script.py
    Traceback (most recent call last):
      File "goodreads_script.py", line 4, in <module>
        book = gc.book(1)
      File "build\bdist.win32\egg\goodreads\client.py", line 87, in book
      File "build\bdist.win32\egg\goodreads\client.py", line 57, in request
      File "build\bdist.win32\egg\goodreads\request.py", line 26, in request
      File "build\bdist.win32\egg\xmltodict.py", line 248, in parse
    xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
    
    C:\Python>

~~It seems to me as though my api key is invalid? I tried resetting it but it gives the same error message. I also tried passing the wrong key to client.GoodreadsClient(), but it also gives the same error message.~~ Edit: Nvm about that; tried it again, it gave a different error message.

Edit2: Okay, according to the error, it's something wrong with the xml that's being fed to the parser. I'm not sure how to go around this.

If you could direct me to where I messed up or what I'm missing, that would be great. :-)

goodreads_script.py was just the file I created following the readme. It goes:

    from goodreads import client
    gc = client.GoodreadsClient(client_key='........', client_secret='........')

    book = gc.book(1)
    book.title

**Comment by sefakilic** [comment]
This seems working fine for me.

```
gc = GoodreadsClient(key, secret)

In [12]: gc.book(1)
Out[12]: Harry Potter and the Half-Blood Prince (Harry Potter, #6)

In [13]: book = gc.book(1)

In [14]: book.title
Out[14]: u'Harry Potter and the Half-Blood Prince (Harry Potter, #6)'
```

**Comment by FatNarwhal** [comment]
Got it to work by installing Linux (ubuntu).
