### ISSUE TITLE
attribute error in deployment

### ISSUE THREAD

**Issue by FatNarwhal** [sefakilic/goodreads#6]
Hi! I'm sorry to bother you again. I get the error message on the logs on Heroku: 

    2015-04-29T07:57:14.996321+00:00 app[web.1]: AttributeError: GoodreadsClient instance has no attribute 'search_books'

Yet, the GoodreadsClient instance has this attribute locally (I am able to execute my script locally).

Doing some digging, I found that when deployed, GoodreadsClient instance does not have the 'search_books' and 'find_author' instances (though the rest of the attributes work fine). I thought it may be a version error on the deployed copy on Heroku as these functions were only added recently, but both my local copy and the deployed copy of the module are up-to-date (based on the requirements.txt file I included in deployment).

**Comment by sefakilic** [comment]
Hi, thanks for using the library and creating issues.

Do you mean you are getting the same error even after you updated the library to the latest version?

It seems working fine for me. [Tests](https://github.com/sefakilic/goodreads/blob/master/tests/client_test.py) also run with no issue.

**Comment by FatNarwhal** [comment]
Yes, I believe so. Perhaps something is wrong with the way I installed it?
 
Here's the contents of a testing script I ran (everything I pushed to the Heroku repo, minus the config file): https://github.com/FatNarwhal/goodreads_testing

In virtualenv, after installing the API wrapper and dependencies, I created a requirements.txt (I generated it by `pip freeze > requirements.txt`). Pushed to heroku, no error messages. I run it, but the logs give me: 

`2015-04-29T15:53:21.707265+00:00 heroku[worker.1]: Starting process with command 'python test.py'
2015-04-29T15:53:22.351911+00:00 heroku[worker.1]: State changed from starting to up
2015-04-29T15:53:23.956453+00:00 app[worker.1]: Traceback (most recent call last):
2015-04-29T15:53:23.956471+00:00 app[worker.1]:   File "test.py", line 12, in <module>
2015-04-29T15:53:23.956478+00:00 app[worker.1]:     query = gc.search_books('the sound and the fury', page= 1, search_field= 'all')
2015-04-29T15:53:23.956535+00:00 app[worker.1]: AttributeError: GoodreadsClient instance has no attribute 'search_books'
2015-04-29T15:53:24.783560+00:00 heroku[worker.1]: State changed from up to crashed
2015-04-29T15:53:24.767565+00:00 heroku[worker.1]: Process exited with status 1`

But in my local environment it runs smoothly, printing `10975` as expected. :-)

My hunch is that heroku is somehow installing the wrong version, but it doesn't give me any error messages and even confirmed during installation that it downloaded goodreads 0.2.3

**Comment by FatNarwhal** [comment]
Hi again! I think I was able to reproduce my issue locally! 

Installing goodreads via requirements.txt 
```
#requirements.txt`
xmltodict
requests
rauth
goodreads
```
and then running in the interpreter 
```
$ pip install -r requirements.txt
...
Successfully installed goodreads-0.2.3 nose-1.3.6 rauth-0.7.1 requests-2.6.2 xmltodict-0.9.2
$ python
>>>from goodreads.client import GoodreadsClient
>>>dir(GoodreadsClient)
['__doc__', '__init__', '__module__', 'auth_user', 'authenticate', 'author', 'base_url', 'book', 'book_review_stats', 'find_groups', 'group', 'list_comments', 'list_events', 'owned_book', 'query_dict', 'recent_reviews', 'request', 'request_oauth', 'review', 'user']
```

**Comment by sefakilic** [comment]
My bad. The version on PyPI didn't have these attributes. I uploaded the latest version. Download it again, please. Thanks!
