### ISSUE TITLE
Is this wrapper Python 2 only?

### ISSUE THREAD

**Issue by avinassh** [sefakilic/goodreads#7]
getting following error in Python3:

    >>> from goodreads import client
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/avi/.tmp/goodreads/venv/lib/python3.4/site-packages/goodreads/client.py", line 2, in <module>
        from session import GoodreadsSession
    ImportError: No module named 'session'

**Comment by sefakilic** [comment]
Yes, the wrapper is for Python 2 only. I am planning to move to Python 3 soon. Any contribution is welcome!

**Comment by avinassh** [comment]
I am mostly a noob, sure, I would love to help in anyway I can :smile: 

Currently it throws unicode errors whenever book name, description etc has unicode characters. How do I handle it?
